title: Teaching Business
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://teachingbusiness.github.io

aux_links:
  Template Repository: https://github.com/teachingbusiness/teachingbusiness.github.io

defaults:
  - scope:
      path: "content" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values: 
      image: true

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/

  # Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/Shield_UnivPittsburgh_3color.png"

# Aux links for the upper right navigation
aux_links:
  "GitHub Repo":
    - "//github.com/teachingbusiness/teachingbusiness.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'

  mermaid:
  # Version of mermaid library - last updates: 2024-11-27
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.4.1"

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true
# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_insensitive

# collections
collections:
  strategy:
    output: true
  comp_think:
    output: true 

just_the_docs:
  collections:
    strategy:
      name: 'Strategic Management'
      nav_fold: true
    comp_think:
      name: 'Computational Thinking'
      nav_fold: true

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: To-do
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red